/**
 * Colors ported from calorie-tracker-ui-v0/app/globals.css (OKLCH → hex via culori).
 * Single source for Tailwind and any API that needs raw hex (tab bar, icons).
 */

const light = {
  background: '#faf8f5',
  foreground: '#2a1f19',
  card: '#fefdfc',
  cardForeground: '#2a1f19',
  popover: '#fefdfc',
  popoverForeground: '#2a1f19',
  primary: '#438c60',
  primaryForeground: '#fefdfc',
  secondary: '#eee7d9',
  secondaryForeground: '#362b25',
  muted: '#f0ebe0',
  mutedForeground: '#6d6059',
  accent: '#e9a679',
  accentForeground: '#3e281b',
  destructive: '#d3721e',
  destructiveForeground: '#592d08',
  border: '#e2ded3',
  input: '#e2ded3',
  ring: '#438c60',
  chart1: '#438c60',
  chart2: '#e9a679',
  chart3: '#a98a55',
  chart4: '#5caeb2',
  chart5: '#e58870',
  sidebar: '#f7f5ef',
  sidebarForeground: '#2a1f19',
  sidebarPrimary: '#438c60',
  sidebarPrimaryForeground: '#fefdfc',
  sidebarAccent: '#eee7d9',
  sidebarAccentForeground: '#362b25',
  sidebarBorder: '#e2ded3',
  sidebarRing: '#438c60',
  success: '#438c60',
  successForeground: '#fefdfc',
  warning: '#e9a679',
  warningForeground: '#592d08',
};

const dark = {
  background: '#17100c',
  foreground: '#ebe7e0',
  card: '#211914',
  cardForeground: '#ebe7e0',
  popover: '#211914',
  popoverForeground: '#ebe7e0',
  primary: '#59a174',
  primaryForeground: '#050e08',
  secondary: '#2f2722',
  secondaryForeground: '#e1ded7',
  muted: '#2f2722',
  mutedForeground: '#938f85',
  accent: '#d1966d',
  accentForeground: '#1e130e',
  destructive: '#a65c20',
  destructiveForeground: '#eec4a9',
  border: '#342c27',
  input: '#342c27',
  ring: '#59a174',
  chart1: '#59a174',
  chart2: '#d1966d',
  chart3: '#967c4f',
  chart4: '#4c9ea2',
  chart5: '#ce816e',
  sidebar: '#1c1410',
  sidebarForeground: '#ebe7e0',
  sidebarPrimary: '#59a174',
  sidebarPrimaryForeground: '#050e08',
  sidebarAccent: '#2f2722',
  sidebarAccentForeground: '#e1ded7',
  sidebarBorder: '#342c27',
  sidebarRing: '#59a174',
  success: '#59a174',
  successForeground: '#050e08',
  warning: '#d1966d',
  warningForeground: '#1e130e',
};

function tailwindColors() {
  return {
    background: light.background,
    foreground: light.foreground,
    card: light.card,
    'card-foreground': light.cardForeground,
    popover: light.popover,
    'popover-foreground': light.popoverForeground,
    primary: light.primary,
    'primary-foreground': light.primaryForeground,
    secondary: light.secondary,
    'secondary-foreground': light.secondaryForeground,
    muted: light.muted,
    'muted-foreground': light.mutedForeground,
    accent: light.accent,
    'accent-foreground': light.accentForeground,
    destructive: light.destructive,
    'destructive-foreground': light.destructiveForeground,
    border: light.border,
    input: light.input,
    ring: light.ring,
    chart1: light.chart1,
    chart2: light.chart2,
    chart3: light.chart3,
    chart4: light.chart4,
    chart5: light.chart5,
    sidebar: light.sidebar,
    'sidebar-foreground': light.sidebarForeground,
    'sidebar-primary': light.sidebarPrimary,
    'sidebar-primary-foreground': light.sidebarPrimaryForeground,
    'sidebar-accent': light.sidebarAccent,
    'sidebar-accent-foreground': light.sidebarAccentForeground,
    'sidebar-border': light.sidebarBorder,
    'sidebar-ring': light.sidebarRing,
    success: light.success,
    'success-foreground': light.successForeground,
    warning: light.warning,
    'warning-foreground': light.warningForeground,
    darkBackground: dark.background,
    darkForeground: dark.foreground,
    darkCard: dark.card,
    darkPopover: dark.popover,
    darkPrimary: dark.primary,
    darkPrimaryForeground: dark.primaryForeground,
    darkSecondary: dark.secondary,
    darkSecondaryForeground: dark.secondaryForeground,
    darkMuted: dark.muted,
    darkMutedForeground: dark.mutedForeground,
    darkAccent: dark.accent,
    darkAccentForeground: dark.accentForeground,
    darkDestructive: dark.destructive,
    darkDestructiveForeground: dark.destructiveForeground,
    darkBorder: dark.border,
    darkInput: dark.input,
    darkRing: dark.ring,
    darkChart1: dark.chart1,
    darkChart2: dark.chart2,
    darkChart3: dark.chart3,
    darkChart4: dark.chart4,
    darkChart5: dark.chart5,
    darkSidebar: dark.sidebar,
    darkSidebarForeground: dark.sidebarForeground,
    darkSidebarPrimary: dark.sidebarPrimary,
    darkSidebarPrimaryForeground: dark.sidebarPrimaryForeground,
    darkSidebarAccent: dark.sidebarAccent,
    darkSidebarAccentForeground: dark.sidebarAccentForeground,
    darkSidebarBorder: dark.sidebarBorder,
    darkSidebarRing: dark.sidebarRing,
    darkSuccess: dark.success,
    darkSuccessForeground: dark.successForeground,
    darkWarning: dark.warning,
    darkWarningForeground: dark.warningForeground,
  };
}

module.exports = { light, dark, tailwindColors };
